// react/pages/index.js
import React from 'react';
import PropTypes from 'prop-types';
import CssBaseline from '@material-ui/core/CssBaseline';
import clsx from 'clsx';
import useMediaQuery from '@material-ui/core/useMediaQuery';
import { useTheme } from '@material-ui/core/styles';
import Head from 'next/head';
import Hidden from '@material-ui/core/Hidden';
import { useSpacing } from '../theme/common';
import Header from '../components/Header';
import BannerSlider from '../components/Home/BannerSlider';
import About from '~/components/Home/About';
import Services from '~/components/Home/Services';
import Expertise from '~/components/Home/Expertise';
import Testimonials from '~/components/Home/Testimonials';
import CaseStudies from '~/components/Home/CaseStudies';
import CallAction from '~/components/CallAction';
import CompanyLogo from '~/components/CompanyLogo';
import Corner from '../components/Home/Corner';
import Footer from '../components/Footer';
import Notification from '../components/Notification';
import brand from '../public/text/brand';

function Landing(props) {
  // Theme breakpoints
  const theme = useTheme();
  const isTablet = useMediaQuery(theme.breakpoints.down('md'));
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  const classes = useSpacing();
  const { onToggleDark, onToggleDir } = props;
  return (
    <React.Fragment>
      <Head>
        <title>
          { brand.agency.name }
          &nbsp;- Home Page
        </title>
      </Head>
      <CssBaseline />
      <div className={classes.mainWrap}>
        <Header
          onToggleDark={onToggleDark}
          onToggleDir={onToggleDir}
          home
        />
        <main className={classes.containerWrap}>
          <section id="home">
            <BannerSlider />
          </section>
          <section
            id="about"
            className={classes.spaceTop}
          >
            <About />
          </section>
          <section
            id="services"
            className={isTablet ? classes.spaceTopShort : classes.spaceTop}
          >
            <Services />
          </section>
          <section
            id="our-expertise"
            className={isMobile ? classes.spaceTopShort : classes.spaceTop}
          >
            <Expertise />
          </section>
          <section
            id="testimonials"
            className={isMobile ? classes.spaceTopShort : classes.spaceTop}
          >
            <Testimonials />
          </section>
          <section id="company" className={clsx(classes.spaceTopShort, classes.spaceBottomShort)}>
            <CompanyLogo />
          </section>
          <section id="case-studies">
            <CaseStudies />
          </section>
          <div
            id="call-to-action"
            className={clsx(classes.spaceBottom, classes.spaceTopShort)}
          >
            <CallAction />
          </div>
        </main>
        <Hidden smDown>
          <Corner />
        </Hidden>
        <Footer toggleDir={onToggleDir} />
        <Hidden mdDown>
          <Notification />
        </Hidden>
      </div>
    </React.Fragment>
  );
}

Landing.getInitialProps = async () => ({
  namespacesRequired: ['common', 'agency-landing'],
});

Landing.propTypes = {
  onToggleDark: PropTypes.func.isRequired,
  onToggleDir: PropTypes.func.isRequired,
};

export default Landing;

// vue/pages/index.vue
<template>
  <div>
    <div class="main-wrap">
      <main-header home />
      <div class="container-wrap">
        <div id="home">
          <banner-slider />
        </div>
        <section
          id="about"
          class="space-top"
        >
          <about />
        </section>
        <section
          id="pricing"
          :class="[isTablet ? 'space-top-short' : 'space-top']"
        >
          <services />
        </section>
        <section
          id="our-expertise"
          :class="[isMobile ? 'space-top-short' : 'space-top']"
        >
          <expertise />
        </section>
        <section
          id="testimonials"
          :class="[isMobile ? 'space-top-short' : 'space-top']"
        >
          <testimonials />
        </section>
        <section id="company" class="space-top-short space-bottom-short">
          <company-logo />
        </section>
        <section id="case-studies">
          <case-studies />
        </section>
        <div
          id="call-to-action"
          class="space-bottom-short"
        >
          <call-action />
        </div>
      </div>
      <main-footer />
      <hidden point="smDown">
        <corner />
      </hidden>
      <hidden point="mdDown">
        <notification />
      </hidden>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import '~/assets/pages';
</style>

<script>
import Header from '~/components/Header'
import Footer from '~/components/Footer'
import CompanyLogo from '~/components/CompanyLogo'
import BannerSlider from '~/components/Home/BannerSlider'
import About from '~/components/Home/About'
import Services from '~/components/Home/Services'
import Expertise from '~/components/Home/Expertise'
import Testimonials from '~/components/Home/Testimonials'
import CaseStudies from '~/components/Home/CaseStudies'
import CallAction from '~/components/CallAction'
import Hidden from '~/components/Hidden'
import Corner from '~/components/Home/Corner'
import Notification from '~/components/Notification'
import brand from '~/static/text/brand'

export default {
  components: {
    'main-header': Header,
    BannerSlider,
    About,
    Services,
    Expertise,
    Testimonials,
    CompanyLogo,
    CaseStudies,
    CallAction,
    Hidden,
    Corner,
    Notification,
    'main-footer': Footer
  },
  head() {
    return {
      title: brand.agency.desc
    }
  },
  computed: {
    isTablet() {
      return this.$mq === 'mdDown' || this.$mq === 'smDown' || this.$mq === 'xsDown' // eslint-disable-line
    },
    isMobile() {
      return this.$mq === 'smDown' || this.$mq === 'xsDown'
    }
  }
}
</script>
